name: Test

on: ['push', 'pull_request']

jobs:
  code:
    name: Test code
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Set up database with docker-compose
        run: docker-compose up -d

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Prisma generate
        run: npm run prisma:generate

      - name: Prima migrate
        run: npm run prisma:migrate

      - name: Run Jest
        run: npm run test -w server
